//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookClubApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Review
    {
        public int ReviewId { get; set; }
        public int BookId { get; set; }

        public string UserName { get; set; }

        public Nullable<int> Rating { get; set; }

        public string Content { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
